export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCTS_DETAILS_REQUEST = 'FETCH_PRODUCTS_DETAILS_REQUEST';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAILURE = 'FETCH_PRODUCTS_DETAILS_FAILURE';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const DELETE_VARIANT_REQUEST = 'DELETE_VARIANT_REQUEST';
export const DELETE_VARIANT_SUCCESS = 'DELETE_VARIANT_SUCCESS';
export const DELETE_VARIANT_FAILURE='DELETE_VARIANT_FAILURE'

