// Action types for payment-related actions
export const CREATE_PAYMENT_LINK_REQUEST = 'CREATE_PAYMENT_LINK_REQUEST';
export const CREATE_PAYMENT_LINK_SUCCESS = 'CREATE_PAYMENT_LINK_SUCCESS';
export const CREATE_PAYMENT_LINK_FAILURE = 'CREATE_PAYMENT_LINK_FAILURE';

export const UPDATE_PAYMENT_INFORMATION_REQUEST = 'UPDATE_PAYMENT_INFORMATION_REQUEST';
export const UPDATE_PAYMENT_INFORMATION_SUCCESS = 'UPDATE_PAYMENT_INFORMATION_SUCCESS';
export const UPDATE_PAYMENT_INFORMATION_FAILURE = 'UPDATE_PAYMENT_INFORMATION_FAILURE';
